// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the thin Wails adapter for FluxDM's application services.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "./internal/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as organization$0 from "./internal/organization/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "./internal/scheduler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as siteprofile$0 from "./internal/siteprofile/models.js";

export function AssignDownloads(input: application$0.AssignDownloadsInput): $CancellablePromise<void> {
    return $Call.ByID(242103517, input);
}

export function CancelDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2532515671, id);
}

export function CheckForUpdates(): $CancellablePromise<application$0.UpdateDTO> {
    return $Call.ByID(2675659504).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearPrivateData(): $CancellablePromise<void> {
    return $Call.ByID(195149017);
}

export function ClearSiteProfileSecrets(id: string): $CancellablePromise<void> {
    return $Call.ByID(2399275979, id);
}

/**
 * ConfirmBrowserDownload claims a parked browser handoff, creates the download
 * record with the cookies captured when the request arrived, and then consumes
 * it. A failed validation or record creation releases the request so the user
 * can correct the destination and try again. The frontend starts the download
 * separately so a queueing failure leaves the queued record visible in the
 * transfer list for the user to retry.
 */
export function ConfirmBrowserDownload(pendingID: string, destinationDir: string, fileName: string, connections: number): $CancellablePromise<application$0.DownloadDTO> {
    return $Call.ByID(341374465, pendingID, destinationDir, fileName, connections).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateDownload(input: application$0.CreateDownloadInput): $CancellablePromise<application$0.DownloadDTO> {
    return $Call.ByID(2173742425, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DefaultDownloadDirectory returns the user's standard Downloads folder for
 * pre-populating the download confirmation dialog.
 */
export function DefaultDownloadDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2102153813);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(988551738, id);
}

/**
 * DeleteCompletedDownloadFiles permanently deletes completed files and their
 * history records. It does not require the Windows shell, so it also supports
 * portable copies running from removable or nonstandard volumes.
 */
export function DeleteCompletedDownloadFiles(ids: string[]): $CancellablePromise<application$0.CompletedFileOperationResult> {
    return $Call.ByID(2502612682, ids).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DeleteDownloadedFile deletes a completed transfer's file and its history
 * record. It never runs or opens the completed file.
 */
export function DeleteDownloadedFile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1132458493, id);
}

export function DeleteQueue(id: string): $CancellablePromise<void> {
    return $Call.ByID(42443685, id);
}

export function DeleteSchedule(id: string): $CancellablePromise<void> {
    return $Call.ByID(3928091207, id);
}

export function DeleteSiteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2660825202, id);
}

/**
 * DiscardBrowserDownload frees a parked browser handoff without creating a
 * download. Called by the frontend when the user cancels or closes the
 * confirmation dialog so cookies do not remain in memory until expiry.
 */
export function DiscardBrowserDownload(pendingID: string): $CancellablePromise<void> {
    return $Call.ByID(1438141719, pendingID);
}

export function DownloadUpdate(): $CancellablePromise<application$0.UpdateDTO> {
    return $Call.ByID(115027584).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExecutePostAction(item: scheduler$0.Schedule): $CancellablePromise<void> {
    return $Call.ByID(1300566376, item);
}

export function ExecuteSchedule(item: scheduler$0.Schedule): $CancellablePromise<void> {
    return $Call.ByID(2994978957, item);
}

export function GetDownload(id: string): $CancellablePromise<application$0.DownloadDTO> {
    return $Call.ByID(3173948315, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetUpdateStatus(): $CancellablePromise<application$0.UpdateDTO> {
    return $Call.ByID(946602336).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HealthCheck confirms that the backend and persistence layer are available.
 */
export function HealthCheck(): $CancellablePromise<application$0.HealthStatus> {
    return $Call.ByID(1288635913).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * HideBrowserConfirmation is invoked only by the compact confirmation surface
 * after it has consumed the last pending browser request.
 */
export function HideBrowserConfirmation(): $CancellablePromise<void> {
    return $Call.ByID(939069458);
}

export function InstallPreparedUpdate(confirmPreview: boolean): $CancellablePromise<void> {
    return $Call.ByID(1322600892, confirmPreview);
}

export function ListCategories(): $CancellablePromise<organization$0.Category[]> {
    return $Call.ByID(1403045529).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListDownloads(): $CancellablePromise<application$0.DownloadDTO[]> {
    return $Call.ByID(2520899730).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListPendingBrowserDownloads returns the metadata needed to recover browser
 * handoffs that arrived before the Wails frontend registered its event
 * listener. Browser cookies remain in the pending store and are never
 * included in this DTO.
 */
export function ListPendingBrowserDownloads(): $CancellablePromise<application$0.DownloadRequestEvent[]> {
    return $Call.ByID(1921217425).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListQueues(): $CancellablePromise<organization$0.Queue[]> {
    return $Call.ByID(3431901717).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListScheduleHistory(limit: number): $CancellablePromise<scheduler$0.History[]> {
    return $Call.ByID(836291328, limit).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListSchedules(): $CancellablePromise<scheduler$0.Schedule[]> {
    return $Call.ByID(1403163153).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListSiteProfiles(): $CancellablePromise<siteprofile$0.Profile[]> {
    return $Call.ByID(1039074356).then(($result: any) => {
        return $$createType16($result);
    });
}

export function MoveCompletedDownloadFiles(input: application$0.MoveCompletedDownloadsInput): $CancellablePromise<application$0.CompletedFileOperationResult> {
    return $Call.ByID(1676485428, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenCompletedDownloadFile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2559263200, id);
}

export function PauseDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(1028494649, id);
}

export function ProbeURL(rawURL: string): $CancellablePromise<application$0.ProbeDTO> {
    return $Call.ByID(3944315818, rawURL).then(($result: any) => {
        return $$createType17($result);
    });
}

export function RecycleCompletedDownloadFiles(ids: string[]): $CancellablePromise<application$0.CompletedFileOperationResult> {
    return $Call.ByID(394831830, ids).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveCompletedDownloadHistory(ids: string[]): $CancellablePromise<application$0.CompletedFileOperationResult> {
    return $Call.ByID(102974978, ids).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveDownloadRecord removes a completed transfer from FluxDM's history but
 * deliberately keeps the downloaded file.
 */
export function RemoveDownloadRecord(id: string): $CancellablePromise<void> {
    return $Call.ByID(2609269192, id);
}

export function RenameCompletedDownloadFile(id: string, fileName: string): $CancellablePromise<application$0.DownloadDTO> {
    return $Call.ByID(3945697978, id, fileName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RestartDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(1893001388, id);
}

export function ResumeDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(687612914, id);
}

export function RevealCompletedDownloadFile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2771618395, id);
}

export function SaveCategory(input: application$0.SaveCategoryInput): $CancellablePromise<organization$0.Category> {
    return $Call.ByID(2195800744, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SaveQueue(input: application$0.SaveQueueInput): $CancellablePromise<organization$0.Queue> {
    return $Call.ByID(4198045279, input).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SaveSchedule(input: application$0.SaveScheduleInput): $CancellablePromise<scheduler$0.Schedule> {
    return $Call.ByID(4069048541, input).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SaveSiteProfile(input: application$0.SaveSiteProfileInput): $CancellablePromise<siteprofile$0.Profile> {
    return $Call.ByID(2025745236, input).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SaveUpdatePreferences(input: application$0.UpdatePreferencesInput): $CancellablePromise<application$0.UpdateDTO> {
    return $Call.ByID(1636394161, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectDestinationDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3071719958);
}

export function SetDownloadBandwidthLimit(id: string, limit: number): $CancellablePromise<void> {
    return $Call.ByID(2574876783, id, limit);
}

export function SetGlobalBandwidthLimit(limit: number): $CancellablePromise<void> {
    return $Call.ByID(3866268384, limit);
}

export function StartDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(3635375267, id);
}

// Private type creation functions
const $$createType0 = application$0.UpdateDTO.createFrom;
const $$createType1 = application$0.DownloadDTO.createFrom;
const $$createType2 = application$0.CompletedFileOperationResult.createFrom;
const $$createType3 = application$0.HealthStatus.createFrom;
const $$createType4 = organization$0.Category.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = application$0.DownloadRequestEvent.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = organization$0.Queue.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = scheduler$0.History.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = scheduler$0.Schedule.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = siteprofile$0.Profile.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = application$0.ProbeDTO.createFrom;
