// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionStartQueue = "start_queue",
    ActionStopQueue = "stop_queue",
    ActionSpeedProfile = "speed_profile",
    ActionRetryFailed = "retry_failed",
};

export class History {
    "id": number;
    "scheduleId": string;
    "runKey": string;
    "scheduledFor": string;
    "executedAt": string;
    "status": string;
    "detail": string;

    /** Creates a new History instance. */
    constructor($$source: Partial<History> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("scheduleId" in $$source)) {
            this["scheduleId"] = "";
        }
        if (!("runKey" in $$source)) {
            this["runKey"] = "";
        }
        if (!("scheduledFor" in $$source)) {
            this["scheduledFor"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("executedAt" in $$source)) {
            this["executedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new History instance from a string or object.
     */
    static createFrom($$source: any = {}): History {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new History($$parsedSource as Partial<History>);
    }
}

export enum MissedPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MissedSkip = "skip",
    MissedRunOnce = "run_once",
};

export enum PostAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PostNone = "none",
    PostExit = "exit",
    PostSleep = "sleep",
    PostHibernate = "hibernate",
    PostShutdown = "shutdown",
};

export class Schedule {
    "id": string;
    "name": string;
    "enabled": boolean;
    "weekdays": number[];
    "timeOfDay": string;
    "action": Action;
    "queueId": string;
    "speedLimit": number;
    "missedPolicy": MissedPolicy;
    "postAction": PostAction;
    "createdAt": string;

    /** Creates a new Schedule instance. */
    constructor($$source: Partial<Schedule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("weekdays" in $$source)) {
            this["weekdays"] = [];
        }
        if (!("timeOfDay" in $$source)) {
            this["timeOfDay"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = Action.$zero;
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = "";
        }
        if (!("speedLimit" in $$source)) {
            this["speedLimit"] = 0;
        }
        if (!("missedPolicy" in $$source)) {
            this["missedPolicy"] = MissedPolicy.$zero;
        }
        if (!("postAction" in $$source)) {
            this["postAction"] = PostAction.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schedule instance from a string or object.
     */
    static createFrom($$source: any = {}): Schedule {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weekdays" in $$parsedSource) {
            $$parsedSource["weekdays"] = $$createField3_0($$parsedSource["weekdays"]);
        }
        return new Schedule($$parsedSource as Partial<Schedule>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
