// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",
    AuthBasic = "basic",
    AuthBearer = "bearer",
};

export class Profile {
    "id": string;
    "name": string;
    "hostPattern": string;
    "authType": AuthType;
    "proxyUrl": string;
    "hasCredentials": boolean;
    "hasCookies": boolean;
    "headerNames": string[];
    "createdAt": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostPattern" in $$source)) {
            this["hostPattern"] = "";
        }
        if (!("authType" in $$source)) {
            this["authType"] = AuthType.$zero;
        }
        if (!("proxyUrl" in $$source)) {
            this["proxyUrl"] = "";
        }
        if (!("hasCredentials" in $$source)) {
            this["hasCredentials"] = false;
        }
        if (!("hasCookies" in $$source)) {
            this["hasCookies"] = false;
        }
        if (!("headerNames" in $$source)) {
            this["headerNames"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headerNames" in $$parsedSource) {
            $$parsedSource["headerNames"] = $$createField7_0($$parsedSource["headerNames"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
