// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Category {
    "id": string;
    "name": string;
    "extensions": string[];
    "destinationDir": string;
    "priority": number;
    "createdAt": string;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("destinationDir" in $$source)) {
            this["destinationDir"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        return new Category($$parsedSource as Partial<Category>);
    }
}

export class Queue {
    "id": string;
    "name": string;
    "priority": number;
    "maxParallel": number;
    "maxConnections": number;
    "bandwidthLimit": number;
    "sequential": boolean;
    "enabled": boolean;
    "createdAt": string;

    /** Creates a new Queue instance. */
    constructor($$source: Partial<Queue> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("maxParallel" in $$source)) {
            this["maxParallel"] = 0;
        }
        if (!("maxConnections" in $$source)) {
            this["maxConnections"] = 0;
        }
        if (!("bandwidthLimit" in $$source)) {
            this["bandwidthLimit"] = 0;
        }
        if (!("sequential" in $$source)) {
            this["sequential"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Queue instance from a string or object.
     */
    static createFrom($$source: any = {}): Queue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Queue($$parsedSource as Partial<Queue>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
