// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../scheduler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as siteprofile$0 from "../siteprofile/models.js";

export class AssignDownloadsInput {
    "downloadIds": string[];
    "categoryId": string;
    "queueId": string;
    "priority": number;

    /** Creates a new AssignDownloadsInput instance. */
    constructor($$source: Partial<AssignDownloadsInput> = {}) {
        if (!("downloadIds" in $$source)) {
            this["downloadIds"] = [];
        }
        if (!("categoryId" in $$source)) {
            this["categoryId"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssignDownloadsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AssignDownloadsInput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("downloadIds" in $$parsedSource) {
            $$parsedSource["downloadIds"] = $$createField0_0($$parsedSource["downloadIds"]);
        }
        return new AssignDownloadsInput($$parsedSource as Partial<AssignDownloadsInput>);
    }
}

/**
 * BrowserIntegrationDTO is a UI-facing status only. The extension path is a
 * local, generated folder suitable for Chromium's Load unpacked picker.
 */
export class BrowserIntegrationDTO {
    "ready": boolean;
    "extensionPath": string;
    "message": string;

    /** Creates a new BrowserIntegrationDTO instance. */
    constructor($$source: Partial<BrowserIntegrationDTO> = {}) {
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("extensionPath" in $$source)) {
            this["extensionPath"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserIntegrationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserIntegrationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserIntegrationDTO($$parsedSource as Partial<BrowserIntegrationDTO>);
    }
}

export class CompletedFileOperationFailure {
    "id": string;
    "message": string;

    /** Creates a new CompletedFileOperationFailure instance. */
    constructor($$source: Partial<CompletedFileOperationFailure> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletedFileOperationFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletedFileOperationFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompletedFileOperationFailure($$parsedSource as Partial<CompletedFileOperationFailure>);
    }
}

export class CompletedFileOperationResult {
    "updated": DownloadDTO[];
    "removedIds": string[];
    "skippedIds": string[];
    "failures": CompletedFileOperationFailure[];

    /** Creates a new CompletedFileOperationResult instance. */
    constructor($$source: Partial<CompletedFileOperationResult> = {}) {
        if (!("updated" in $$source)) {
            this["updated"] = [];
        }
        if (!("removedIds" in $$source)) {
            this["removedIds"] = [];
        }
        if (!("skippedIds" in $$source)) {
            this["skippedIds"] = [];
        }
        if (!("failures" in $$source)) {
            this["failures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletedFileOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletedFileOperationResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updated" in $$parsedSource) {
            $$parsedSource["updated"] = $$createField0_0($$parsedSource["updated"]);
        }
        if ("removedIds" in $$parsedSource) {
            $$parsedSource["removedIds"] = $$createField1_0($$parsedSource["removedIds"]);
        }
        if ("skippedIds" in $$parsedSource) {
            $$parsedSource["skippedIds"] = $$createField2_0($$parsedSource["skippedIds"]);
        }
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField3_0($$parsedSource["failures"]);
        }
        return new CompletedFileOperationResult($$parsedSource as Partial<CompletedFileOperationResult>);
    }
}

export class CreateDownloadInput {
    "url": string;
    "destinationDir": string;
    "fileName": string;
    "connections": number;
    "bandwidthLimit": number;
    "categoryId": string;
    "queueId": string;
    "priority": number;
    "siteProfileId": string;

    /** Creates a new CreateDownloadInput instance. */
    constructor($$source: Partial<CreateDownloadInput> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("destinationDir" in $$source)) {
            this["destinationDir"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("bandwidthLimit" in $$source)) {
            this["bandwidthLimit"] = 0;
        }
        if (!("categoryId" in $$source)) {
            this["categoryId"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("siteProfileId" in $$source)) {
            this["siteProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateDownloadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateDownloadInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateDownloadInput($$parsedSource as Partial<CreateDownloadInput>);
    }
}

export class DownloadDTO {
    "id": string;
    "url": string;
    "finalUrl": string;
    "fileName": string;
    "destinationPath": string;
    "tempPath": string;
    "state": string;
    "totalBytes": number;
    "downloadedBytes": number;
    "rangeSupported": boolean;
    "restartRequired": boolean;
    "mimeType": string;
    "createdAt": string;
    "startedAt": string | null;
    "completedAt": string | null;
    "lastError": string;
    "retryCount": number;
    "connections": number;
    "segmentCount": number;
    "bandwidthLimit": number;
    "categoryId": string;
    "queueId": string;
    "queuePosition": number;
    "priority": number;
    "siteProfileId": string;

    /** Creates a new DownloadDTO instance. */
    constructor($$source: Partial<DownloadDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("finalUrl" in $$source)) {
            this["finalUrl"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("destinationPath" in $$source)) {
            this["destinationPath"] = "";
        }
        if (!("tempPath" in $$source)) {
            this["tempPath"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("rangeSupported" in $$source)) {
            this["rangeSupported"] = false;
        }
        if (!("restartRequired" in $$source)) {
            this["restartRequired"] = false;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("retryCount" in $$source)) {
            this["retryCount"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("segmentCount" in $$source)) {
            this["segmentCount"] = 0;
        }
        if (!("bandwidthLimit" in $$source)) {
            this["bandwidthLimit"] = 0;
        }
        if (!("categoryId" in $$source)) {
            this["categoryId"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = "";
        }
        if (!("queuePosition" in $$source)) {
            this["queuePosition"] = 0;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("siteProfileId" in $$source)) {
            this["siteProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadDTO($$parsedSource as Partial<DownloadDTO>);
    }
}

/**
 * DownloadRequestEvent is the Wails-facing payload emitted when a browser
 * handoff arrives. It carries only the data the UI needs to render a
 * confirmation dialog; browser session cookies remain server-side and are
 * never included here.
 */
export class DownloadRequestEvent {
    "pendingId": string;
    "url": string;
    "suggestedFilename": string;
    "referrer": string;

    /** Creates a new DownloadRequestEvent instance. */
    constructor($$source: Partial<DownloadRequestEvent> = {}) {
        if (!("pendingId" in $$source)) {
            this["pendingId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("suggestedFilename" in $$source)) {
            this["suggestedFilename"] = "";
        }
        if (!("referrer" in $$source)) {
            this["referrer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRequestEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadRequestEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadRequestEvent($$parsedSource as Partial<DownloadRequestEvent>);
    }
}

export class HealthStatus {
    "status": string;
    "version": string;
    "platform": string;
    "checkedAt": string;

    /** Creates a new HealthStatus instance. */
    constructor($$source: Partial<HealthStatus> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthStatus($$parsedSource as Partial<HealthStatus>);
    }
}

export class MoveCompletedDownloadsInput {
    "downloadIds": string[];
    "destinationDir": string;

    /** Creates a new MoveCompletedDownloadsInput instance. */
    constructor($$source: Partial<MoveCompletedDownloadsInput> = {}) {
        if (!("downloadIds" in $$source)) {
            this["downloadIds"] = [];
        }
        if (!("destinationDir" in $$source)) {
            this["destinationDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveCompletedDownloadsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveCompletedDownloadsInput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("downloadIds" in $$parsedSource) {
            $$parsedSource["downloadIds"] = $$createField0_0($$parsedSource["downloadIds"]);
        }
        return new MoveCompletedDownloadsInput($$parsedSource as Partial<MoveCompletedDownloadsInput>);
    }
}

export class ProbeDTO {
    "url": string;
    "finalUrl": string;
    "fileName": string;
    "totalBytes": number;
    "mimeType": string;
    "etag": string;
    "lastModified": string;
    "rangeSupported": boolean;

    /** Creates a new ProbeDTO instance. */
    constructor($$source: Partial<ProbeDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("finalUrl" in $$source)) {
            this["finalUrl"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("etag" in $$source)) {
            this["etag"] = "";
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }
        if (!("rangeSupported" in $$source)) {
            this["rangeSupported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeDTO($$parsedSource as Partial<ProbeDTO>);
    }
}

export class SaveCategoryInput {
    "id": string;
    "name": string;
    "extensions": string[];
    "destinationDir": string;
    "priority": number;

    /** Creates a new SaveCategoryInput instance. */
    constructor($$source: Partial<SaveCategoryInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("destinationDir" in $$source)) {
            this["destinationDir"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveCategoryInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveCategoryInput {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        return new SaveCategoryInput($$parsedSource as Partial<SaveCategoryInput>);
    }
}

export class SaveQueueInput {
    "id": string;
    "name": string;
    "priority": number;
    "maxParallel": number;
    "maxConnections": number;
    "bandwidthLimit": number;
    "sequential": boolean;
    "enabled": boolean;

    /** Creates a new SaveQueueInput instance. */
    constructor($$source: Partial<SaveQueueInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("maxParallel" in $$source)) {
            this["maxParallel"] = 0;
        }
        if (!("maxConnections" in $$source)) {
            this["maxConnections"] = 0;
        }
        if (!("bandwidthLimit" in $$source)) {
            this["bandwidthLimit"] = 0;
        }
        if (!("sequential" in $$source)) {
            this["sequential"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveQueueInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveQueueInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveQueueInput($$parsedSource as Partial<SaveQueueInput>);
    }
}

export class SaveScheduleInput {
    "id": string;
    "name": string;
    "enabled": boolean;
    "weekdays": number[];
    "timeOfDay": string;
    "action": scheduler$0.Action;
    "queueId": string;
    "speedLimit": number;
    "missedPolicy": scheduler$0.MissedPolicy;
    "postAction": scheduler$0.PostAction;
    "confirmPowerAction": boolean;

    /** Creates a new SaveScheduleInput instance. */
    constructor($$source: Partial<SaveScheduleInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("weekdays" in $$source)) {
            this["weekdays"] = [];
        }
        if (!("timeOfDay" in $$source)) {
            this["timeOfDay"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = scheduler$0.Action.$zero;
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = "";
        }
        if (!("speedLimit" in $$source)) {
            this["speedLimit"] = 0;
        }
        if (!("missedPolicy" in $$source)) {
            this["missedPolicy"] = scheduler$0.MissedPolicy.$zero;
        }
        if (!("postAction" in $$source)) {
            this["postAction"] = scheduler$0.PostAction.$zero;
        }
        if (!("confirmPowerAction" in $$source)) {
            this["confirmPowerAction"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveScheduleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveScheduleInput {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weekdays" in $$parsedSource) {
            $$parsedSource["weekdays"] = $$createField3_0($$parsedSource["weekdays"]);
        }
        return new SaveScheduleInput($$parsedSource as Partial<SaveScheduleInput>);
    }
}

export class SaveSiteProfileInput {
    "id": string;
    "name": string;
    "hostPattern": string;
    "authType": siteprofile$0.AuthType;
    "username": string;
    "password": string;
    "bearerToken": string;
    "cookies": string;
    "headers": { [_ in string]?: string };
    "proxyUrl": string;
    "proxyUsername": string;
    "proxyPassword": string;

    /** Creates a new SaveSiteProfileInput instance. */
    constructor($$source: Partial<SaveSiteProfileInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostPattern" in $$source)) {
            this["hostPattern"] = "";
        }
        if (!("authType" in $$source)) {
            this["authType"] = siteprofile$0.AuthType.$zero;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("bearerToken" in $$source)) {
            this["bearerToken"] = "";
        }
        if (!("cookies" in $$source)) {
            this["cookies"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("proxyUrl" in $$source)) {
            this["proxyUrl"] = "";
        }
        if (!("proxyUsername" in $$source)) {
            this["proxyUsername"] = "";
        }
        if (!("proxyPassword" in $$source)) {
            this["proxyPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSiteProfileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveSiteProfileInput {
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        return new SaveSiteProfileInput($$parsedSource as Partial<SaveSiteProfileInput>);
    }
}

export class UpdateDTO {
    "currentVersion": string;
    "channel": string;
    "autoDownload": boolean;
    "phase": string;
    "availableVersion": string;
    "releaseNotesUrl": string;
    "downloadedBytes": number;
    "totalBytes": number;
    "lastCheckedAt": string;
    "lastError": string;
    "preview": boolean;
    "canInstall": boolean;
    "installedVersion": string;
    "installedAt": string;

    /** Creates a new UpdateDTO instance. */
    constructor($$source: Partial<UpdateDTO> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("autoDownload" in $$source)) {
            this["autoDownload"] = false;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("availableVersion" in $$source)) {
            this["availableVersion"] = "";
        }
        if (!("releaseNotesUrl" in $$source)) {
            this["releaseNotesUrl"] = "";
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("lastCheckedAt" in $$source)) {
            this["lastCheckedAt"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = false;
        }
        if (!("canInstall" in $$source)) {
            this["canInstall"] = false;
        }
        if (!("installedVersion" in $$source)) {
            this["installedVersion"] = "";
        }
        if (!("installedAt" in $$source)) {
            this["installedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateDTO($$parsedSource as Partial<UpdateDTO>);
    }
}

export class UpdatePreferencesInput {
    "channel": string;
    "autoDownload": boolean;

    /** Creates a new UpdatePreferencesInput instance. */
    constructor($$source: Partial<UpdatePreferencesInput> = {}) {
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("autoDownload" in $$source)) {
            this["autoDownload"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePreferencesInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdatePreferencesInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdatePreferencesInput($$parsedSource as Partial<UpdatePreferencesInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DownloadDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CompletedFileOperationFailure.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
