// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {context} from '../models';
import {scheduler} from '../models';
import {organization} from '../models';
import {siteprofile} from '../models';

export function AssignDownloads(arg1:application.AssignDownloadsInput):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function ClearPrivateData():Promise<void>;

export function ClearSiteProfileSecrets(arg1:string):Promise<void>;

export function CreateDownload(arg1:application.CreateDownloadInput):Promise<application.DownloadDTO>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteQueue(arg1:string):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteSiteProfile(arg1:string):Promise<void>;

export function ExecutePostAction(arg1:context.Context,arg2:scheduler.Schedule):Promise<void>;

export function ExecuteSchedule(arg1:context.Context,arg2:scheduler.Schedule):Promise<void>;

export function GetDownload(arg1:string):Promise<application.DownloadDTO>;

export function HealthCheck():Promise<application.HealthStatus>;

export function ListCategories():Promise<Array<organization.Category>>;

export function ListDownloads():Promise<Array<application.DownloadDTO>>;

export function ListQueues():Promise<Array<organization.Queue>>;

export function ListScheduleHistory(arg1:number):Promise<Array<scheduler.History>>;

export function ListSchedules():Promise<Array<scheduler.Schedule>>;

export function ListSiteProfiles():Promise<Array<siteprofile.Profile>>;

export function MoveCompletedDownloadFiles(arg1:application.MoveCompletedDownloadsInput):Promise<application.CompletedFileOperationResult>;

export function OpenCompletedDownloadFile(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function ProbeURL(arg1:string):Promise<application.ProbeDTO>;

export function RecycleCompletedDownloadFiles(arg1:Array<string>):Promise<application.CompletedFileOperationResult>;

export function RemoveCompletedDownloadHistory(arg1:Array<string>):Promise<application.CompletedFileOperationResult>;

export function RenameCompletedDownloadFile(arg1:string,arg2:string):Promise<application.DownloadDTO>;

export function RestartDownload(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RevealCompletedDownloadFile(arg1:string):Promise<void>;

export function SaveCategory(arg1:application.SaveCategoryInput):Promise<organization.Category>;

export function SaveQueue(arg1:application.SaveQueueInput):Promise<organization.Queue>;

export function SaveSchedule(arg1:application.SaveScheduleInput):Promise<scheduler.Schedule>;

export function SaveSiteProfile(arg1:application.SaveSiteProfileInput):Promise<siteprofile.Profile>;

export function SelectDestinationDirectory():Promise<string>;

export function SetDownloadBandwidthLimit(arg1:string,arg2:number):Promise<void>;

export function SetGlobalBandwidthLimit(arg1:number):Promise<void>;

export function StartDownload(arg1:string):Promise<void>;
