// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignDownloads(arg1) {
  return window['go']['main']['App']['AssignDownloads'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearPrivateData() {
  return window['go']['main']['App']['ClearPrivateData']();
}

export function ClearSiteProfileSecrets(arg1) {
  return window['go']['main']['App']['ClearSiteProfileSecrets'](arg1);
}

export function CreateDownload(arg1) {
  return window['go']['main']['App']['CreateDownload'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['main']['App']['DeleteQueue'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteSiteProfile(arg1) {
  return window['go']['main']['App']['DeleteSiteProfile'](arg1);
}

export function ExecutePostAction(arg1, arg2) {
  return window['go']['main']['App']['ExecutePostAction'](arg1, arg2);
}

export function ExecuteSchedule(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSchedule'](arg1, arg2);
}

export function GetDownload(arg1) {
  return window['go']['main']['App']['GetDownload'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function ListQueues() {
  return window['go']['main']['App']['ListQueues']();
}

export function ListScheduleHistory(arg1) {
  return window['go']['main']['App']['ListScheduleHistory'](arg1);
}

export function ListSchedules() {
  return window['go']['main']['App']['ListSchedules']();
}

export function ListSiteProfiles() {
  return window['go']['main']['App']['ListSiteProfiles']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ProbeURL(arg1) {
  return window['go']['main']['App']['ProbeURL'](arg1);
}

export function RestartDownload(arg1) {
  return window['go']['main']['App']['RestartDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveCategory(arg1) {
  return window['go']['main']['App']['SaveCategory'](arg1);
}

export function SaveQueue(arg1) {
  return window['go']['main']['App']['SaveQueue'](arg1);
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function SaveSiteProfile(arg1) {
  return window['go']['main']['App']['SaveSiteProfile'](arg1);
}

export function SelectDestinationDirectory() {
  return window['go']['main']['App']['SelectDestinationDirectory']();
}

export function SetDownloadBandwidthLimit(arg1, arg2) {
  return window['go']['main']['App']['SetDownloadBandwidthLimit'](arg1, arg2);
}

export function SetGlobalBandwidthLimit(arg1) {
  return window['go']['main']['App']['SetGlobalBandwidthLimit'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
